<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-16T16:33:09 IST" name="Suite" finished-at="2022-07-16T16:33:15 IST" duration-ms="6302">
    <groups>
    </groups>
    <test started-at="2022-07-16T16:33:09 IST" name="Test01" finished-at="2022-07-16T16:33:15 IST" duration-ms="6302">
      <class name="test.Testclass">
        <test-method is-config="true" signature="InitBrowser()[pri:0, instance:test.Testclass@35d019a3]" started-at="2022-07-16T16:32:56 IST" name="InitBrowser" finished-at="2022-07-16T16:33:09 IST" duration-ms="12662" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitBrowser -->
        <test-method is-config="true" signature="beforeS()[pri:0, instance:test.Testclass@35d019a3]" started-at="2022-07-16T16:33:09 IST" name="beforeS" finished-at="2022-07-16T16:33:09 IST" depends-on-methods="test.Driver.InitBrowser" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeS -->
        <test-method is-config="true" signature="obj()[pri:0, instance:test.Testclass@35d019a3]" started-at="2022-07-16T16:33:09 IST" name="obj" finished-at="2022-07-16T16:33:09 IST" duration-ms="115" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- obj -->
        <test-method signature="test()[pri:0, instance:test.Testclass@35d019a3]" started-at="2022-07-16T16:33:09 IST" name="test" finished-at="2022-07-16T16:33:15 IST" duration-ms="5812" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method signature="test2()[pri:0, instance:test.Testclass@35d019a3]" started-at="2022-07-16T16:33:15 IST" name="test2" finished-at="2022-07-16T16:33:15 IST" duration-ms="21" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [login] but found [OrangeHRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [login] but found [OrangeHRM]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at test.Testclass.test2(Testclass.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:test.Testclass@35d019a3]" started-at="2022-07-16T16:33:15 IST" name="afterSuite" finished-at="2022-07-16T16:33:16 IST" duration-ms="811" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- test.Testclass -->
    </test> <!-- Test01 -->
  </suite> <!-- Suite -->
</testng-results>
